import { KJUR } from 'jsrsasign';

/**
 * A sample function to generate a token to join a video SDK session
 * In a production app, this should be generated by the server -- never the frontend --
 * as it is very insecure
 *
 * @param topic your session topic
 * @param passWord your session password
 */

export function generateSessionToken(topic: string, passWord: string) {
  let signature = '';
  try {
    const iat = Math.round(new Date().getTime() / 1000);
    const exp = iat + 60 * 60 * 2;

    // Header
    const oHeader = { alg: 'HS256', typ: 'JWT' };
    // Payload
    const oPayload = {
      app_key: process.env.ZOOM_SDK_KEY,
      iat,
      exp,
      tpc: topic,
      pwd: passWord,
    };
    // Sign JWT, password=616161
    const sHeader = JSON.stringify(oHeader);
    const sPayload = JSON.stringify(oPayload);
    signature = KJUR.jws.JWS.sign('HS256', sHeader, sPayload, process.env.ZOOM_SDK_SECRET);
  } catch (e) {
    console.error(e);
  }
  return signature;
}
