name: Heymate web app dev deployment

on:
  push:
    branches: [ master ]
env:
  AWS_REGION: us-east-1   
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Configure AWS Credentials Action For GitHub Actions"
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Build
      run: |
        npm install
        npm run build:heymate-dev
        cd dist
        aws s3 sync . s3://${{ secrets.S3_BUCKET }}
        cd ..
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --path "/*"
        
